title: Mazhar Iqbal # your name (or website title) here
logo: /images/Picture3.png  # your photo (or logo) here
description: 

  <a href="file:///Volumes/T7/Download_7/MazharResume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/mazhar-iqbal-96baa4258/">LinkedIn</a>
  
  
  <p align="justify">
  I am pursuing Ph.D. degree in Physics at The University of Texas at Dallas.
  <br><br>
  The focus of my study is exploring the effects of Global Environmental Change on bird distribution,
  population dynamics, and migration patterns. 
  My research involves analyzing climate data sourced from the Climate Research Unit at the University of East Anglia,
  alongside bird data collected through the Breeding Bird Survey. Leveraging advanced Machine Learning techniques,
  I aim to assess the  relationships between climate variables and bird behavior
  <br><br>
  </p>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

